# Copyright 2023 The Authors (see AUTHORS file)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Workflow that handles AOD requests cleanup.
name: 'aod-cleanup'

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'main'
    paths:
      - 'tool.yaml'
      - 'iam.yaml'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-aod-cleanup'
  cancel-in-progress: true

jobs:
  cleanup:
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    uses: 'abcxyz/access-on-demand/.github/workflows/cleanup.yml@sqin/fix' # Change here to pin the tag or commit.
    # To specify inputs, change the repository variables.
    # Details: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
    with:
      workload_identity_provider: '${{ vars.workload_identity_provider }}'
      service_account: '${{ vars.service_account }}'
      aod_cli_version: '${{ vars.aod_cli_version || ''0.1.9'' }}'
      go_version: '${{ vars.go_version || ''1.21'' }}'
      pr_number: '${{ github.event.pull_request.number }}'
      branch: '${{ github.event.pull_request.head.ref }}'
