# Copyright 2023 The Authors (see AUTHORS file)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Workflow that handles AOD requests.
name: 'aod-handle'
on:
  pull_request:
    types:
      - 'labeled'
      - 'opened'
      - 'synchronize'
  pull_request_review:
    types:
      - 'submitted'
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-aod-request-handle'
  cancel-in-progress: true
jobs:
  handle:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    uses: 'abcxyz/access-on-demand/.github/workflows/handle.yml@625f685a62f42ddfa48c8c6da767ae8a0961a2e8' # Change here to pin the tag or commit. ratchet:abcxyz/access-on-demand/.github/workflows/handle.yml@v0.1.10
    # To specify inputs, change the repository variables.
    # Details: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
    with:
      workload_identity_provider: '${{ vars.workload_identity_provider }}'
      service_account: '${{ vars.service_account }}'
      aod_cli_version: '${{ vars.aod_cli_version || ''0.1.10'' }}'
      go_version: '${{ vars.go_version || ''1.21'' }}'
