# Workflow that adds a note to every AOD request.
name: 'aod-note'

on:
  pull_request:
    types:
      - 'opened'
    paths:
      - 'iam.yaml'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-aod-note'
  cancel-in-progress: true

jobs:
  validate:
    permissions:
      pull-requests: 'write'
    uses: 'abcxyz/access-on-demand/.github/workflows/note.yml@d27c31c0b847df8001cf3a2049282b77f4d453c5' # Change here to pin the tag or commit.
    with:
      # To specify expiry_hours (the number of hours to keep an AOD PR open
      # since last updated), change the repository variables.
      # Details: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
      expiry_hours: '${{ vars.expiry_hours || 24 }}'
