# Move this to access-on-demand repo.
name: 'aod-request-checker'

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      is_iam:
        value: ${{ jobs.check.outputs.is_iam }}
      is_command:
        value: ${{ jobs.check.outputs.is_command }}
jobs:
  check:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      is_iam: '${{ steps.iam.outputs.any_changed }}'
      is_command: '${{ steps.command.outputs.any_changed }}'
    steps:
      - name: 'Checkout Triggering Branch'
        uses: 'actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab' # ratchet:actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - id: 'iam'
        uses: 'tj-actions/changed-files@84ed30e2f4daf616144de7e0c1db59d5b33025e3' # ratchet:tj-actions/changed-files@v35
        with:
          files: 'iam.yaml'
      - id: 'command'
        uses: 'tj-actions/changed-files@84ed30e2f4daf616144de7e0c1db59d5b33025e3' # ratchet:tj-actions/changed-files@v35
        with:
          files: 'command.yaml'
