# Move this to access-on-demand repo.
name: 'aod-request-checker'

on:
  workflow_call:
    inputs:
      path:
        description: 'The file path to check.'
        type: 'string'
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      is_aod:
        value: ${{ jobs.check.outputs.is_aod }}
jobs:
  check:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      is_aod: '${{ steps.changed-file.outputs.any_changed }}'
    steps:
      - name: 'Checkout Triggering Branch'
        uses: 'actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab' # ratchet:actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - id: 'changed-file'
        uses: 'tj-actions/changed-files@84ed30e2f4daf616144de7e0c1db59d5b33025e3' # ratchet:tj-actions/changed-files@v35
        with:
          files: |
            ${{ inputs.path }}