# Workflow that validates a AOD requests.
name: 'aod-validate'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'iam.yaml'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-aod-request-validation'
  cancel-in-progress: true

jobs:
  validate:
    uses: 'abcxyz/access-on-demand/.github/workflows/validate.yml@08e700894c010ca2110fe2a99b964bc27986b120' # Change here to pin the tag or commit.
    # To specify inputs, change the repository variables.
    # Details: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
    with:
      aod_cli_version: '${{ vars.aod_cli_version || ''latest'' }}'
      go_version: '${{ vars.go_version || ''1.20'' }}'
